### ISSUE TITLE
Not displaying breakpoints

### ISSUE THREAD

**Issue by wesort** [emmetio/re-view#13]
The new design doesn't show any of the breakpoints. The following example has at least three but shows only one view.

![not recognising breakpoints](https://cloud.githubusercontent.com/assets/3920126/12961275/752b2c1c-d037-11e5-9f42-762fb7624b3b.png)

FYI: viewing on a Chromebook Pixel 2 on stable channel.

**Comment by sergeche** [comment]
Just pushed v2.0.1, should fix this issue
