### ISSUE TITLE
Setting pre-sets modal has overlapping text

### ISSUE THREAD

**Issue by wesort** [emmetio/re-view#14]
After hitting the "+" preset button the device list has a visual glitch of overlapping text. This disappears after mousing-over any device names.

![overlapping device text](https://cloud.githubusercontent.com/assets/3920126/12961335/d35c082e-d037-11e5-80d1-7b51d66816ac.png)

FYI: Tested on Chromebook Pixel 2 on Stable channel.

**Comment by sergeche** [comment]
Can’t reproduce it on OSX, will try to install Chrome OS later

**Comment by wesort** [comment]
That's fixed now.
