### ISSUE TITLE
Too many breakpoint screens on Bootstrap site

### ISSUE THREAD

**Issue by smlombardi** [emmetio/re-view#15]
I have a basic Bootstrap site where, to my knowledge, we didn't add any custom breakpoints.  When viewed with the extension, there are way too many screens in the browser to be much use.  Perhaps present a list of media queries present and present a UI to check off which ones to display?

**Comment by sergeche** [comment]
Added breakpoints picker in v2.1, see https://github.com/emmetio/re-view-chrome/releases/tag/v2.1.0

**Comment by smlombardi** [comment]
Great!
