### ISSUE TITLE
Excessive scrolling with Magic Mouse 2

### ISSUE THREAD

**Issue by smlombardi** [emmetio/re-view#16]
This might be related to the fact that my site displayed many breakpoint views, but we I just touched the scroll surface of my Magic Mouse 2 the page "took off" scrolling horizontally like mad and I could not stop it to be able to manually control scroll and had to close extension.

**Comment by sergeche** [comment]
There’s a vertical scroll overriding for those who doesn’t use devices like Magic Mouse. Try to wait a bit after scrolling and move cursor around to focus on view, does it helps?

**Comment by smlombardi** [comment]
Yes, it has.  I also donated.

**Comment by sergeche** [comment]
Thanks! :+1:
