### ISSUE TITLE
Show if preview viewport is scaled down

### ISSUE THREAD

**Issue by wesort** [emmetio/re-view#18]
Currently it's a bit unclear whether the preview container is at full scale or not. Could something be added to the UI to make this obvious? A zoom icon or border colour perhaps?

**Comment by sergeche** [comment]
In v2.1, a scale factor is displayed in view label, see https://github.com/emmetio/re-view-chrome/releases/tag/v2.1.0

**Comment by wesort** [comment]
The trouble is that the text is tiny and unreadable (a bug I presume). Bringing this up to a suitable size would be good, but I still reckon a visual indicator would be better.

![text is tiny](https://cloud.githubusercontent.com/assets/3920126/13146722/0c86112c-d64f-11e5-8f1e-b05fadeedf4d.png)

**Comment by sergeche** [comment]
>  text is tiny and unreadable (a bug I presume)

It’s  because overall view is downscaled to fit your screen. Hold Shift and use mouse wheel to zoom in/out.

Maybe we talk about different things? The scale indicator is added to Breakpoints View. In Device Wall, each view contents is downscaled only if there’s no `<meta name="viewport">` tag on the page or its size is larger than viewport width

**Comment by wesort** [comment]
I take your point that there is a difference between Breakpoint View & Device Wall. Both are great perspectives. 

I like that the view is scaled down, but on Device Wall the text that notes what the device is with dimensions & scale is also scaled down. Why can't that text (circled in red below) be not-scaled?

![scale text](https://cloud.githubusercontent.com/assets/3920126/13148015/63669f12-d653-11e5-9bf3-8cc4edd27d28.png)

**Comment by sergeche** [comment]
It’s not that easy to implement: the overall views container is scaled down so I have to scale up inner labels manually, which is bad in terms of performance and code complexity. Also these labels may overlap adjacent view and become unreadable. 

I’ll think about adding a more readable alternative for scaled Device Wall (please create a new issue).

**Comment by wesort** [comment]
Ok, fair enough - I don't know your code.
