### ISSUE TITLE
Breakpoint displayed without being in CSS

### ISSUE THREAD

**Issue by robincham** [emmetio/re-view#20]
When I review page breakpoints, I see a display for "max 480px 480x100%" even though I don't have a media query set for that width, and I have the choice for 480px in the 'breakpoints' selection tab.  Why?

Also, it seems the 480px view displays styles set for @media only screen and (max-width:768px) instead of 768px view.

**Comment by sergeche** [comment]
Well, that’s because somewhere on your page there’s a CSS that contains such `@media` rule. Re:view just scans all the CSS, it doesn’t create new queries

**Comment by robincham** [comment]
Of course, you are correct.  I found the @media 480px ref in a small,
additional css file.  I just didn't research enough.

But, when I make changes to my main css file in the @media only screen and
(max-width:768px){ } section, the changes do not appear in the Re:view
breakpoint display titled max:768px, but display in the breakpoint display
for max-width:480px on localhost or on server. I've attached in .png format
a screenshot of what I see in Re:view.  Suggestions welcome.

/*************_MEDIA ADJUSTMENTS**_*************/
@media only screen and (max-width: 768px){
  html {font-size:10px;}
  .pledge {top:-100px;margin:0 auto;padding:1px 5px 8px;}
  .pledge h2 {font-size:1.2rem;}
  .pledge h1 {font-size:1.5rem;}
  #why {padding:40px 0;}
  #how {padding:60px 0;}
  .icon {width:4rem;}

  /_STYLING CHANGE_/
  .capLogo {width:130%;}

  footer span.copyright {font-size:1rem;}
}

@media only screen and (max-width:480px){}

R

On Sun, Feb 21, 2016 at 5:01 AM, Sergey Chikuyonok <notifications@github.com

**Comment by sergeche** [comment]
There are many possible options depending on your editing workflow. It’s better to create an animated gif/video of your entire screen that displays problem

**Comment by robincham** [comment]
S:

When you say "entire screen that displays problem", what do you mean?  The
screenshot shows what I see in Re:view display: the @media changes only
show up in the 480px max box instead of the 768px max box as required in
the css snippet I included.

For what it's worth, when I manually resize the screen in Chrome, the css
@media changes display properly.

Feedback welcome.

And, since I used your previous version of Re:view for a long time without
this problem, is that version somehow still available?

R

On Sun, Feb 21, 2016 at 9:28 AM, Sergey Chikuyonok <notifications@github.com

**Comment by sergeche** [comment]
I don’t see any screenshot attached so I don’t know what exactly you did with CSS.

And no, previous version is not available and it’s not an option, it’s better to fix problems in new extension.

**Comment by robincham** [comment]
OK, here's the css that produces the false breakpoint display at 480px and
an attached screenshot of how it looks in Re:view.

/*************_MEDIA ADJUSTMENTS**_*************/
@media only screen and (max-width: 768px){
  html {font-size:10px;}
  .pledge {top:-100px;margin:0 auto;padding:1px 5px 8px;}
  .pledge h2 {font-size:1.2rem;}
  .pledge h1 {font-size:1.5rem;}
  #why {padding:40px 0;}
  #how {padding:60px 0;}
  .icon {width:4rem;}

  /_STYLING CHANGE_/
  .capLogo {width:130%;}

  footer span.copyright {font-size:1rem;}
}

@media only screen and (max-width:480px){}

**Comment by sergeche** [comment]
There’s still no screenshot

**Comment by sergeche** [comment]
You should upload screenshot [here](https://github.com/emmetio/re-view/issues/20) instead of attaching it into mail message

**Comment by robincham** [comment]
OK, find screenshot here. Thanks.
![review_screenshot](https://cloud.githubusercontent.com/assets/5941366/13225324/9374282a-d949-11e5-9d90-84eab390df5d.png)

**Comment by sergeche** [comment]
Is this web-site online? Try to right-click on `.capLogo` inside 768 box, pick Inspect and check out styles applied to this element: you might have another CSS rule that overrides element size

**Comment by robincham** [comment]
Yes, site online: http://web-wrx.com/CAP/BIGshortIndex.php using
BIGshortPledge.css

Inspecting the image in 768 box shows ,capLogo width:30% even though @media
(max-width:768) { .capLogo {width:130%;} } in BIGshortPledge.css

Inspecting the image in 480 box shows ,capLogo width:130%

Again, when resizing screen in Chrome manually, all works as expected.

Scratching my head on this one . . . bet it's a simple mistake on my part,
though I don't see where, so I'm just checking with you for feedback.

**Comment by sergeche** [comment]
Found the problem, happens on Windows only: Re:view creates views with respect of scrollbar size (required to display exact width in Device Wall) which actually creates larger viewports. In your case 768 box is actually 785px wide so your media query doesn’t match. Will push fix soon

**Comment by robincham** [comment]
Excellent. I image coding extensions for Chrome in several OS systems is
interesting, especially when tiny bugs like this crop up.

Glad I could help . . . if "help" is the word.

R

**Comment by sergeche** [comment]
Just pushed v2.1.1 with fix
