### ISSUE TITLE
Chrome 52 - change device menu dissapeared

### ISSUE THREAD

**Issue by justynawasiak** [emmetio/re-view#27]
After installing the 52 actualization on chrome the menu to change devices dissapeared.
I have only the "Breakpoint view" and "Device wall". 
There should be also a menu where I could change the default device wall settings, choose any device or define my own devices. Now it is gone.

**Comment by sergeche** [comment]
Just pushed v2.1.2, should fix this problem

**Comment by justynawasiak** [comment]
It works now, thank you :)
