### ISSUE TITLE
Resize handle y-axis

### ISSUE THREAD

**Issue by planetflash** [emmetio/re-view#5]
Love the plugin and has already become an integral part of my workflow. 

It would be great to have a resize handle for the y-axis as well as the x-axis for quick testing over vertical overflow and layout issues.

**Comment by InSuperposition** [comment]
:+1:

**Comment by sergeche** [comment]
Not sure about real use case. Right now all windows are stretched vertically so you can adjust browser window height to get desired result. Introducing y-resizer may lead to a new UX problems like global scrolling.

**Comment by sergeche** [comment]
The new Device Wall mode in v2 should work better for testing on device-sized viewports
