### ISSUE TITLE
Font injection using http causes an error on https sites.

### ISSUE THREAD

**Issue by patacra** [emmetio/re-view#9]
Thanks for your wonderful plugin!!!

In app.js, the function used to inject Google's "Lato" font unfortunately loads over http. This causes some errors when you are visiting a site over https. Using a protocol-free URL (such as //fonts.googleapis.com) could be a solution but this will cause errors when viewing html files that are not served from a web server (such as a local file).

For this reason, I think it should be possible to just replace http://font.googleapis.com by https://fonts.googleapis.com. I don't think it does any harm to load a resource over https if you are visiting a page which is not served over https.

```
function injectFont() {
    var fontCSS = document.createElement('link');
    fontCSS.setAttribute('rel', 'stylesheet');
    fontCSS.setAttribute('href', 'https://fonts.googleapis.com/css?family=Lato');
    document.head.appendChild(fontCSS);
}
```

Hope this works!

**Comment by sergeche** [comment]
Not relevant for v2 anymore since there’s no external resources
